[package]
name = "openentropy-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Core entropy harvesting library â€” 47 hardware noise sources, raw or SHA-256 conditioned"
readme = "README.md"

[dependencies]
sha2 = { workspace = true }
flate2 = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

log = { workspace = true }
getrandom = { workspace = true }
